# Generated by Django 5.1.4 on 2025-01-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='media')),
                ('product_name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('discount', models.CharField(blank=True, max_length=150)),
                ('discount_name', models.CharField(blank=True, max_length=150)),
                ('buy_months', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
